"on":
    push:
        branches:
            - porter
name: Deploy to claude-agent-container
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply -f ./porter.yaml
              env:
                PORTER_APP_NAME: claude-agent-container
                PORTER_CLUSTER: "5241"
                PORTER_DEPLOYMENT_TARGET_ID: 04c55b73-6772-40b3-b545-1074789d4c14
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "8935"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_8935_5241 }}
